project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Échantillonnage La Grave
      - href: stations_2022.qmd
        text: Stations 2022

format:
  html:
    theme: cosmo
    toc: true


